name: Docker Image CI

on:
  push:
    branches: [ "enhancements" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PW }}
        
    - uses: actions/checkout@v2
      with:
        context: .
    - name: Build & push the Docker image
      run: |
        docker build . --tag quay.io/${{ secrets.QUAY_ID }}/numalign-rewritten
        docker push quay.io/${{ secrets.QUAY_ID }}/numalign-rewritten
