name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PW }}
        
    - name: Build & push the Docker image
      uses: actions/checkout@v3
      run: |
      docker build . --tag quay.io/${{ secrets.QUAY_ID }}/numalign-rewritten/numalign:$(date +%s) # change this to latest
      docker push quay.io/${{ secrets.QUAY_ID }}/numalign-rewritten/numalign:$(date +%s)
