name: release workflow
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup golang
        uses: actions/setup-go@v3
        id: go
        with:
          go-version: 1.20
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build numalign
        # The binary will be saved under ../../build as numalign
        run: make

      - name: release the tool binary
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          artifacts: ./build/numalign
